### ISSUE TITLE
Rebase const-generics branch

### ISSUE THREAD

**Issue by varkor** [varkor/rust#1]
@yodaldevoid: I'd like to rebase the `const-generics` branch on to `master` to fix up the few merge conflicts that have arisen, and also avoid having to rebuild the new version of LLVM after switching between `const-generics` and other branches each time. I was originally going to wait until https://github.com/rust-lang/rust/pull/48149 had been merged, but as that'll probably take a little while longer, I'd rather do it first now.

Can I force push a rebased version of the branch, or will that cause issues for you at the moment?

**Comment by yodaldevoid** [comment]
Feel free to go ahead. I probably won't be able to work on this for a few weeks as I am currently swamped by school work.

**Comment by varkor** [comment]
I've been holding off on making more changes to `const-generics` until the two other refactoring PRs get merged. After that, though, there are only a few `TODO`s left — though I ran into some compilation errors when trying to compile the examples, so there are definitely still some rough patches that need to be looked into before we have something that works.

**Comment by varkor** [comment]
@yodaldevoid: just thought it'd be good to update you on where I am with this (though you've probably noticed the lack of movement) — I've been busy and I'm not going to have time for the next month and a half to work on const generics, other than continuing to push the refactoring PRs through. In about 6 weeks, though, I should have a lot more time and plan to start working hard!

Just from some of the rebasing I did after miri: there's quite a lot that's changed, both for better (some of our `// TODO`s are irrelevant now) and for the worse (fixing everything) — and this will be even more true after the two generics PRs get merged, so it might even be more convenient overall this way.

I'm not sure when the lazy normalisation problems will hit (it seems there are at least _some_ uses of const generics that should be fine), but integration with Chalk is already beginning to start, so it might even line up well with our branch. I'm optimistic we could be starting to merge things in by the end of summer...

**Comment by yodaldevoid** [comment]
I've been keeping an eye on the refactoring PRs. I should finally have time to work on this for long enough to move it forward around the same time that the first one goes through.
